version: '3'
services:
  spark-master:
    build: .
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4042:4042" # exposed a range of ports for the Spark UI
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./scripts:/scripts
      - ./secrets:/secrets
      - ./files:/files
      - ./notebooks:/notebooks

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.2
    container_name: jupyter
    ports:
      - "8888:8888"  # Jupyter Notebook port
      - "4041:4040"  # Spark UI port
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077  # Connect Jupyter to Spark master
      - PYSPARK_PYTHON=python3
      - JUPYTER_ENABLE_LAB=no  # Disable JupyterLab and use Jupyter Notebook
    command: start-notebook.sh --NotebookApp.token=''  # Start Jupyter Notebook without token authentication
    volumes:
      - ./secrets:/home/jovyan/work/secrets
      - ./notebooks:/home/jovyan/work/notebooks
      - ./notebooks/files:/home/jovyan/work/notebooks/files
    depends_on:
      - spark-master
